DROP TABLE IF EXISTS activity;
DROP TABLE IF EXISTS crop;
DROP TABLE IF EXISTS parcel;
DROP TABLE IF EXISTS app_user;

CREATE TABLE app_user (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          full_name VARCHAR(100) NOT NULL,
                          email VARCHAR(254) NOT NULL UNIQUE,
                          password VARCHAR(100) NOT NULL,
                          role VARCHAR(20) NOT NULL
);

CREATE TABLE crop (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      name VARCHAR(100) NOT NULL,
                      type VARCHAR(100) NOT NULL,
                      planting_date DATE NOT NULL,
                      user_id BIGINT NOT NULL,

                      CONSTRAINT fk_crop_user
                          FOREIGN KEY (user_id)
                              REFERENCES app_user(id)
);

CREATE TABLE parcel (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        location VARCHAR(200) NOT NULL,
                        size DOUBLE PRECISION NOT NULL
                            CHECK (size > 0),
    soil_type VARCHAR(100) NOT NULL,
    user_id BIGINT NOT NULL,

    CONSTRAINT fk_parcel_user
        FOREIGN KEY (user_id)
        REFERENCES app_user(id)
);

CREATE TABLE activity (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          description VARCHAR(255) NOT NULL,
                          date DATE NOT NULL,
                          type VARCHAR(100) NOT NULL,
                          user_id BIGINT NOT NULL,

                          CONSTRAINT fk_activity_user
                              FOREIGN KEY (user_id)
                                  REFERENCES app_user(id)
);

CREATE INDEX idx_crop_user_id
    ON crop(user_id);

CREATE INDEX idx_parcel_user_id
    ON parcel(user_id);

CREATE INDEX idx_activity_user_id
    ON activity(user_id);